### ISSUE TITLE
Integration with machine

### ISSUE THREAD

**Issue by joques** [ifandelse/machina.postal#2]
Hi all,
I have been looking at the machina.postal example in the repository and it is really not clear to me how to integrate machina and machina.postal on the server side (using node.js). Suppose I have a bunch of fsm that I'd like to create using machina. Sometimes in the examples the subscribe method is used, sometimes the publish method is used directly. What is the right way to add each fsm with its own channel to the message bus?
Also, when an fsm reaches a final state is it automatically discarded from the message bus, or is it the responsibility of the developer? I am asking this because it is an in-memory message bus
Any help will be appreciated.
José

**Comment by joques** [comment]
I finally figured out how it works. Now I am interested in whether it is discarded once the reaches the final state.
Thanks
José

**Comment by ifandelse** [comment]
@joques I sincerely apologize, this issue slipped through the cracks on me - I didn't mean to neglect answering you! I'm glad you got things working in node.js. To answer the question you still have: it doesn't auto-dispose the message bus integration when your FSM reaches a final state, however I just updated machina.postal to v0.4.0, which includes a tear down method that's added to the machina.Fsm prototype, so you could do something along these lines:

``` javascript
var fsm = new machina.Fsm({
    initialState: "uninitialized",
    states: {
        uninitialized: {
            start: "started"
        },
        started : {
            "some.input" : function(args) {
                doStuffWith(args);
                this.transition("stopped");
            }
        },
        stopped: {
            _onEnter: function() {
                // prevent any more messages from
                // being processed or published by this FSM
                this.removeAllBusIntegration();
            }
        }
    }
});
```
