### ISSUE TITLE
How do I destroy FSM used together with machina.postal?

### ISSUE THREAD

**Issue by hippich** [ifandelse/machina.postal#3]
Not sure where this should happen, in machina.js or machina.postal. 

I have created FSM and using machina.postal to interact with it. Now, how I can destroy FSM and prevent it from reacting to any new events?

I am creating FSM like this:
var Controller = Machina.Fsm.extend({....})
var controller = new Controller();

But after I do "controller = null;" it still reacts to events published in bus.

**Comment by ifandelse** [comment]
@hippich my apologies for the delay in replying. Have had a _lot_ going on personally (good stuff....like my 3rd son being born), so I'm behind in general. This is a great question - and I'm sorry you're having issues with it still reacting to messages after you need it disposed of. unfortunately I haven't added a formal mechanism to neatly unsubscribe - which is a horrible oversight on my part. However, I glanced at the code to refresh my memory, and in the [wireUp](https://github.com/ifandelse/machina.postal/blob/master/src/adapter.js#L28) method I noticed that I'm storing channel and subscription info off of machina.bus. Specifically, I'm storing the subscriptions that invoke FSM input handlers in an array under `machina.bus.channels[handlerChannel]._subscriptions` (where `handlerChannel` is the fsm namespace plus any namespace suffix you might have added to the machina.postal configuration).  That being the case, you should be able to iterate over that array and call unsubscribe on the subscriptions. Hopefully that works as a temporary solution until I get a proper API in place for it.

**Comment by ifandelse** [comment]
@hippich I updated machina.postal so that it stores the subscription/channel instances on the affected FSM (under this._bus), and it also adds methods to the machina.Fsm prototype - specifically one called `removeAllBusIntegration` that will allow you to prevent any further messages from being handled by the FSM, as well as prevent it from publishing any events out, etc. Check out version 0.4.0 and let me know if that works for what you need: https://github.com/ifandelse/machina.postal thanks!

**Comment by hippich** [comment]
Thanx! I should be able to testdrive it this week!

**Comment by ifandelse** [comment]
@hippich sounds good - I'll keep this open until I hear how it goes.

**Comment by ifandelse** [comment]
@hippich just checking in - any chance this took care of the issue for you?

**Comment by demisx** [comment]
@hippich Can you please tell us if this worked?

**Comment by hippich** [comment]
Sorry... I moved on from the project where I had this issue. From looking at the code it seems like it solves problem, but I can't test it anymore. I would say as it is right now issue should be closed :)

**Comment by ifandelse** [comment]
@demisx Apologies for the delay. When I get a moment, I'll try and follow up on the most recent changes I made to verify that the problem was truly resolved.
